config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'profile/new'
  # get 'profile/create'
  # post 'profile/create'
  # get 'profile/show'
  # get 'profile/edit'
  # get 'profile/update'
  # get 'profile/destroy'
  # get 'authentication/login'
  # get 'sessions/login'
  # post 'sessions/login'
  # get 'sessions/home'
  # get 'sessions/profile'
  # get 'sessions/settings'
  # post 'users/new'
  # get 'users/create'
  # post 'users/create'
  # get 'users/login'
  get 'authentication/login'
  get 'authentication/signup'
  get 'welcome/index'
  post 'authentication/create'
  get  'authentication/create'
  post 'authentication/authentication_login'
  get 'authentication/destroy'
  post 'authentication/destroy'

  
  resources :profiles

  resources :user do
    resources :articles
  end

  resources :articles do
    resources :comments
  end

  root 'authentication#login'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 4 }
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
	
  belongs_to :article
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord
  belongs_to :user

  mount_uploader :image, ImageUploader

  validates_presence_of :image

  validate :image_size_validation

  private

  def image_size_validation
    errors[:image] << 'should be less than 500KB' if image.size > 0.5.megabytes
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_one :profile

  has_many :articles

  validates :password_digest, presence: true,
                              length: { within: 6..12 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  http_basic_authenticate_with name: 'hamza', password: '1234', except: %i[index show]

  before_action :authentication_login

  def index
    @user = User.find_by(id: session[:user_id])

    @articles = @user.articles
  end

  # create a new instance variable and Allow to make new article in Article class
  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save

      redirect_to @article
    else

      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)

      redirect_to @article
    else
      render 'edit'
     end
  end

  def destroy
    @article = Article.find(params[:id])

    @article.destroy

    redirect_to articles_path
  end

  private

  def authentication_login
    redirect_to authentication_login_path if session[:user_id].blank?
  end

  def article_params
    params.require(:article).permit(:user_id, :title, :text)
  end
end

app/controllers/authentication_controller.rb
# frozen_string_literal: true

class AuthenticationController < ApplicationController
  # before_action :authentication_login

  def create
    @user = User.create(username: params[:username], password_digest: params[:password])

    if @user

      session[:user_id] = @user.id

      flash[:notice] = 'You signed up successfully'

      redirect_to articles_path

    else

      flash[:notice] = 'Problem with signup Password feild must not be empty'

      redirect_to authentication_login_path
    end
  end

  def authentication_login
    @user = User.find_by(username: params[:username], password_digest: params[:password])

    if @user

      session[:user_id] = @user.id

      redirect_to articles_path

    else

      flash[:notice] = 'Invalid Username or Password'

      redirect_to authentication_login_path
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to authentication_login_path, alert: "You've successfully logged out! Login again?"
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authentication_login

  http_basic_authenticate_with name: 'hamza', password: '1234', only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def authentication_login
    redirect_to authentication_login_path if session[:user_id].blank?
      end

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :authentication_login
  # before_action :check_profile_presence, only: [:new, :create]

  def index
    @user = User.find_by(id: session[:user_id])

    @profile = @user.profile
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)

    if @profile.save

      redirect_to @profile

    else

      render 'new'

    end
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])

    if @profile.update(profile_params)

      redirect_to @profile

    else

      render 'edit'
    end
  end

  private

  def authentication_login
    redirect_to authentication_login_path if session[:user_id].blank?
  end

  def check_profile_presence
    # redirect_to user_profile_path if current_user.profile.exists?
  end

  def profile_params
    params.require(:profile).permit(:user_id, :image, :firstname, :lastname, :address, :city, :state, :zipcode)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def login
    user = User.authenticate(params[:username], params[:password])

    if user

      flash[:notice] = 'Wow Welcome again, you logged in'

      redirect_to Welcome_index_path

    else

      flash[:notice] = 'Invalid Username or Password'

    end
  end

  def home; end

  def profile; end

  def settings; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save

      flash[:notice] = 'You signed up successfully'

      redirect_to welcome_index_path

    else

      flash[:notice] = 'Form is invalid'

      render 'new'
    end
  end

  def login; end

  private

  def user_params
    params.require(:user).permit(:username, :password, :salt, :encrypted_password)
end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  before_action :authentication_login

  def index
    puts 'My Blog is ready'
  end

  private

  def authentication_login
    if session[:user_id].blank?

      redirect_to authentication_signup_path, alert: 'Problem in Signup Try again'

   end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/authentication_helper.rb
# frozen_string_literal: true

# AuthenticationHelper
module AuthenticationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/profile_helper.rb
# frozen_string_literal: true

module ProfileHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>

      <%= form.hidden_field :user_id , value: session[:user_id] %>
      
    </div>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title  , class: "title_feild" %>
  </p>
  <h4 class="checkfeilds_error" id="title_feild"></h4>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text  , class: "body_feild" %>
  </p>

  <h4 class="checkfeilds_error" id="text_field"></h4>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<!--The arguments to form_with could be model objects, say, model: @article which would cause the helper to fill in the form with the fields of the object. Passing in a symbol scope (scope: :article) just creates the fields but without anything filled into them.-->

<!--Passing the article object to the method, will automatically create url for submitting the edited article form. This option tells Rails that we want this form to be submitted via the PATCH HTTP method which is the HTTP method you're expected to use to update resources according to the REST protocol.

-->
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Your Articles in Blog</h1><hr>

<!--This link will allow you to bring up the form that lets you create a new article.-->
<h2>Click below to create new articles</h2>
<%= link_to 'New article' , new_article_path  %><br>
<h2>Click below for your profile</h2>
<%= link_to 'Profile' , profiles_path  %><br>
<h2>Click here to Logout</h2>

 <a href = "<%=authentication_destroy_path %>">Logout</a>


<hr>

<table>
	<tr>
		<th>Title</th>
		<th>Text</th>
		<th>Actions</th>
	</tr>


<%= @articles.each do |article|%>
	<tr>
		<td><%=article.title %></td>
		<td><%=article.text %></td>
		<td><%= link_to 'Show', article_path(article) %></td>
		<td><%= link_to 'Edit', edit_article_path(article) %></td>
		<td><%= link_to 'Delete', article_path(article),method: :delete, data: { confirm: 'Are you sure?' } %></td>


	</tr>

	<%end%>

	</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<!--When you call form_with, you pass it an identifying scope for this form. In this case, it's the symbol :article. This tells the form_with helper what this form is for. Inside the block for this method, the FormBuilder object - represented by form - is used to build two labels and two text fields, one each for the title and text of an article. Finally, a call to submit on the form object will create a submit button for the form.

-->


<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
	<strong>Title:</strong>
	<%= @article.title %>
</p>
<p>
	<strong>Text:</strong>
	<%= @article.text %>
</p>



<!--This adds a form on the Article show page that creates a new comment by calling the CommentsController create action. The form_with call here uses an array, which will build a nested route, such as /articles/1/comments.-->
 
<h2>Add a comment:</h2>

<%= render @article.comments %>

<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>






<!--go back to the index action as well, so that people who are viewing a single article can go back and view the whole list again:-->

app/views/authentication/create.html.erb
<<%= form_tag("/authentication/create", method: "post") do %>

<% if @user.errors.any? %>
	<% @user.errors.full_messages.each do |msg| %>
	<div class="alert alert-danger"><%=msg%></div>
	<% end %>
<% end %> 
  <%= label_tag(:username, "Username:") %>

  <%= text_field_tag(:username) %>

  <%= label_tag(:password, "Password:") %>

  <%= text_field_tag(:password) %>

  <%= submit_tag("Signup") %>

 <% end %>

app/views/authentication/login.html.erb
<div class="container-fluid">

<h2 class="bg-light" align="center"><strong><b>Welcome to My Blog <em>Login|Signup</em> first!!</b></strong></h2>
<div align="left">
	
<%= form_tag("/authentication/authentication_login" , method: "post") do %>

<p>
  <%= label_tag(:username, "Enter Username:") %><br>

  <%= text_field_tag(:username) %><br>

  </p>

  <span class="check-field" id="usernamecheck"></span>


<p>
  <%= label_tag(:password, " Enter Password:") %><br>

  <%= password_field_tag(:password) %><br>

  </p>

<span class="check-field" id="passwordcheck"></span> <br>

  <%= submit_tag "Login" , class: 'submitform' %><br>

 <% end %>

 </div>

<hr>
<h3>If you are not a user first click here to signup</h3>
<a href = "<%=authentication_signup_path %>">Signup</a>

</div>

app/views/authentication/signup.html.erb
<div class="container-fluid">
<h2 align="center" class="bg-light"><strong><b>Signup Here!!</b></strong></h2>

<%= form_tag("/authentication/create" , method: "post") do %>


<p>
	<%= label_tag(:username, "Enter Username:") %><br>

	<%= text_field_tag(:username) %><br>
</p>

<span class="check-field" id="usernamecheck"></span>

<p>

  <%= label_tag(:password, "Enter Password:") %><br>

  <%= password_field_tag(:password) %><br>
  
</p>

	<span class="check-field" id="passwordcheck"></span><br>
	

  <%= submit_tag "Signup" , class: 'submitform' %><br>

 <% end %>

</div>

<div class="container-fluid">

 <hr>

<h2>If you are already a member click the link below for login</h2>
  <a href = "<%=authentication_login_path %>">Login</a>
</div>

app/views/comments/_comment.html.erb
<p>
	<strong>Commenter:</strong>
	<%= comment.commenter%>
</p>

<p>
    
  <strong>Commenter:</strong>
	<%= comment.body%>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<div class="container-fluid">
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
</div>

app/views/profiles/_form.html.erb
<div class="container-fluid">

<%= form_with(model: @profile, html: { multipart: true } ) do |form| %>
 
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@profile.errors.count, "error") %> prohibited
        
        this profile from being saved:
      </h2>
      <ul>
        <% @profile.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <div>

      <%= form.hidden_field :user_id , value: session[:user_id] %>
      
    </div>

  <p>
    <%= form.label :image %><br><br>
    <%= form.file_field :image %>
  </p>

  <h4 class="checkfeilds_error" id="profile-image"></h4>

  <p>

    <%= form.label :firstname%><br>
    <%= form.text_field :firstname %>
  </p>

  <h4 class="checkfeilds_error" id="firstname"></h4>

   <p>
    <%= form.label :lastname%><br>
    <%= form.text_field :lastname %>
  </p>

  <h4 class="checkfeilds_error" id="lastname"></h4>
 
  <p>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </p>

  <h4 class="checkfeilds_error" id="address"></h4>

  <p>
    <%= form.label :city%><br>
    <%= form.text_field :city %>
  </p>

  <h4 class="checkfeilds_error" id="city"></h4>

  <p>
    <%= form.label :state%><br>
    <%= form.text_field :state %>
  </p>

  <h4 class="checkfeilds_error" id="state"></h4>

  <p>
    <%= form.label :zipcode%><br>
    <%= form.text_field :zipcode %>
  </p>

  <h4 class="checkfeilds_error" id="zip"></h4>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
</div>

app/views/profiles/create.html.erb
<h1>Profile#create</h1>
<p>Find me in app/views/profile/create.html.erb</p>

app/views/profiles/destroy.html.erb
<h1>Profile#destroy</h1>
<p>Find me in app/views/profile/destroy.html.erb</p>

app/views/profiles/edit.html.erb
<h1>Edit your profile here</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<%= link_to "Back" ,welcome_index_path%>
<h1>My Profile</h1>

<div class="well">
	<span><b>Frist Name:</b></span>
	<p><%=@profile.firstname %></p>
	<span><b>Last Name:</b></span>
	<p><%=@profile.lastname %></p>
	<span><b>Address:</b></span>
	<p><%=@profile.address %></p>
	<%= link_to "Show Full Profile" ,profile_path(@profile)%>
	<hr>
</div>

app/views/profiles/new.html.erb
<h1 class="bg-light" align="center">Add a new Profile</h1>


<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<h1>User Profile</h1>

<p>
  <strong>Image:</strong>
  <%= image_tag @profile.image.thumb.url %>
</p>

<p>
	<strong>First Name:</strong>
	<%= @profile.firstname %>
</p>
<p>
	<strong>Last Name:</strong>
	<%= @profile.lastname %>
</p>
<p>
	<strong>Address:</strong>
	<%= @profile.address %>
</p>
<p>
	<strong>City:</strong>
	<%= @profile.city %>
</p>
<p>
	<strong>State:</strong>
	<%= @profile.state %>
</p>
<p>
	<strong>Zip code:</strong>
	<%= @profile.zipcode %>
</p>

<p>
  <%=	link_to "Back", profiles_path %>
</p>
<p>
  <%=	link_to "Edit", edit_profile_path %>
</p>

app/views/profiles/update.html.erb
<h1>Profile#update</h1>
<p>Find me in app/views/profile/update.html.erb</p>

app/views/users/create.html.erb
<% @page_title = "Signup" %>

<div class="Sign_Form">

  <h1>Sign Up</h1>

  <%= form_for( :user, :url => {:controller => 'users', :action => 'create'}) do |f| %>

    <p> Username:</br> <%= f.text_field :username%> </p>

    <p> Password:</br> <%= f.password_field :password%></p>
    
    <%= f.submit :Signup %>


  <% end %>
  
</div>

app/views/users/login.html.erb
<div class= "Login_Form">

  <h1>Log in</h1>

  <%= form_tag(:action => 'login') do %>

    <p>Username or Email:</br> <%= text_field_tag(:username) %></p> 

    <p>Password:</br> <%= password_field_tag(:password) %></p> 
    
    <%= submit_tag("Log In") %>
  <% end %>
</div>

app/views/users/new.html.erb
<% @page_title = "Signup" %>

<div class="Sign_Form">

  <h1>Sign Up</h1>

  <%= form_for( :user, :url => {:controller => 'users', :action => 'create'}) do |f| %>

    <p> Username:</br> <%= f.text_field :username%> </p>

    <p> Password:</br> <%= f.password_field :password%></p>
    
    <%= f.submit :Signup %>

  <% end %>
  
</div>

app/views/welcome/index.html.erb
<h1>Welcome to BLOG application!</h1>

<h2>Please click the down link to check your blogs</h2>

<%= link_to 'My Blog' , articles_path %>

 <h2>If There is no article posted right now click here to create a new article first</h2>

<%= link_to 'New article' , new_article_path  %>


<h3>Click here to see all Users</h3>

<%= link_to 'User Profile' , profiles_path %>



<h2>Click here to Logout</h2>

 <a href = "<%=authentication_destroy_path %>">Logout</a>